### ISSUE TITLE
Embed Textures?

### ISSUE THREAD

**Issue by vod1003** [Luctaris/blender-import-glr#4]
Textures are missing when exporting as .fbx from Blender. I tried packing the images with the external data trick but that didn't seem to work as well.

**Comment by Luctaris** [comment]
Support for external exporters and file formats is somewhat out of the scope of this project. I can't control how scenes using my tool are imported and interpreted by other software.

This project sets up a custom shader node layout for each material used in the scene.

I couldn't find a suitable file format that can support texture blending, vertex color information, texture mirroring, fog information, etc... which is why I opted to create my own custom .glr file format and associated importer for Blender.

If you want an importer for Maya, 3ds Max, 4D cinema, etc... a custom importer addon/plugin/script will need to be made to interpret the .glr file format for that tool.
